services:
  redis:
    image: redis:8.8
    container_name: gecko-redis
    restart: unless-stopped
    volumes: 
      - redis-data:/data
    ports: 
      - 6380:6379
  db:
    image: mongo:7.0.34-jammy
    container_name: gecko-mongo
    restart: unless-stopped
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: gecko-rabbitmq
    restart: unless-stopped
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
volumes:
  redis-data:
  mongo-data:
  rabbitmq-data:
