services:
  redis:
    image: redis:8.8
    container_name: gecko-redis
    restart: unless-stopped
    volumes: 
      - redis-data:/data
    ports: 
      - 6380:6379
  db:
    image: mongo:7.0.34-jammy
    container_name: gecko-mongo
    restart: unless-stopped
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: gecko-rabbitmq
    restart: unless-stopped
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build: .
    container_name: gecko-api
    restart: unless-stopped
    ports:
     - 8000:8000
    env_file: .env
    environment:
      APP_MONGODB_URL: mongodb://db:27017
      APP_REDIS_URL: redis://redis:6379
      APP_RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
     - db
     - redis
     - rabbitmq
  
  consumer:
    build: .
    container_name: gecko-consumer
    restart: unless-stopped
    command: python -m app.consumer
    env_file: .env
    environment: 
      APP_MONGODB_URL: mongodb://db:27017
      APP_REDIS_URL: redis://redis:6379
      APP_RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
volumes:
  redis-data:
  mongo-data:
  rabbitmq-data:
